<?xml version="1.0" encoding="UTF-8"?><testrun name="FriendServiceTest" project="demo" tests="2" started="2" failures="1" errors="0" ignored="0">
  <testsuite name="com.example.demo.service.FriendServiceTest" time="1.373" displayname="FriendServiceTest" uniqueid="[engine:junit-jupiter]/[class:com.example.demo.service.FriendServiceTest]">
    <testcase name="addedFriendSuccessfully" classname="com.example.demo.service.FriendServiceTest" time="1.354" displayname="added friend successfully" uniqueid="[engine:junit-jupiter]/[class:com.example.demo.service.FriendServiceTest]/[method:addedFriendSuccessfully()]"/>
    <testcase name="friendAlreadyExists" classname="com.example.demo.service.FriendServiceTest" time="0.018" displayname="friend already exists" uniqueid="[engine:junit-jupiter]/[class:com.example.demo.service.FriendServiceTest]/[method:friendAlreadyExists()]">
      <failure>org.opentest4j.AssertionFailedError: Expected com.example.demo.service.exception.ResourceAlreadyExists to be thrown, but nothing was thrown.
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:73)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:35)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3128)
	at com.example.demo.service.FriendServiceTest.friendAlreadyExists(FriendServiceTest.java:105)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

</failure>
    </testcase>
  </testsuite>
</testrun>
